;; Software Testing and TDD Workshop Notes
(bufshow-start
 [(bufshow-split-right "../basics/__tests__/sum.js" "../basics/sum.js")
  ("../basics/__tests__/format-username.js")
  ("../blackjack/backlog/ticket1.md")
  ("../blackjack/app/__tests__/event-creators.test.js")
  ("../blackjack/app/event-creators.js")
  ("../blackjack/app/__tests__/reducer.test.js")
  ("../blackjack/app/reducer.js")
  ("../blackjack/app/__tests__/render-ui.test.js")
  ("../blackjack/app/render-ui.js")
  ("../blackjack/index.js")
  ("../blackjack/backlog/ticket2.md")
  ("../blackjack/app/__tests__/event-creators.test.js")
  ("../blackjack/app/event-creators.js")
  ("../blackjack/app/__tests__/reducer.test.js")
  ("../blackjack/app/reducer.js")
  ("../blackjack/app/__tests__/render-ui.test.js")
  ("../blackjack/app/render-ui.js")
  ("../blackjack/index.js")
  ("../blackjack/backlog/ticket3.md")
  ("../blackjack/app/__tests__/selectors.test.js")
  ("../blackjack/app/selectors.js")
  ("../blackjack/app/__tests__/render-ui.test.js")
  ("../blackjack/app/render-ui.js")
  ("../blackjack/index.js")
  ])
