;; Software Testing and TDD Workshop Notes
(bufshow-start
 [(bufshow-split-right "../basics/__test__/sum.test.js" "../basics/sum.js")
  (bufshow-split-right "../basics/__test__/format-username.test.js" "../basics/format-username.js")
  ("note1.org")
  ("../blackjack/backlog/ticket1.md")
  ("../blackjack/app/__test__/event-creators.test.js")
  ("../blackjack/app/event-creators.js")
  ("../blackjack/app/__test__/reducer.test.js")
  ("../blackjack/app/reducer.js")
  ("../blackjack/app/__test__/render-ui.test.js")
  ("../blackjack/app/render-ui.js")
  ("../blackjack/index.js")
  ("../blackjack/backlog/ticket2.md")
  ("../blackjack/app/__test__/event-creators.test.js")
  ("../blackjack/app/event-creators.js")
  ("../blackjack/app/__test__/reducer.test.js")
  ("../blackjack/app/reducer.js")
  ("../blackjack/app/__test__/render-ui.test.js")
  ("../blackjack/app/render-ui.js")
  ("../blackjack/index.js")
  ("../blackjack/backlog/ticket3.md")
  ("../blackjack/app/__test__/selectors.test.js")
  ("../blackjack/app/selectors.js")
  ("../blackjack/app/__test__/render-ui.test.js")
  ("../blackjack/app/render-ui.js")
  ("../blackjack/index.js")
  ])
